repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [ commit-msg ]
        args: [ "--config=.configs/commitlint.config.js" ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: no-commit-to-branch
        stages: [ prepare-commit-msg, merge-commit, push ]
        always_run: false
  - repo: https://github.com/mpalmer/action-validator
    rev: v0.5.1
    hooks:
      - id: action-validator
        stages: [ commit-msg ]
  - repo: local
    hooks:
      - id: run-all-before-push
        name: Run All Before Push
        entry: .git-hooks/run-all-before-push.sh
        language: script
        stages: [ push ]
      - id: before-commit
        name: Before Commit
        entry: .git-hooks/before-commit.sh
        language: script
        stages: [ commit-msg ]
