name: 'Create Changelog'
description: 'create changelog base standard-version package'
author: 'Payadel'

# Here we define the inputs, which can be set
# from the workflow file and are consumed in our code
inputs:
  version:
    description: 'specific version?'
    required: false
    default: ''
  ignore-same-version-error:
    description: 'ignore the same version error or not?'
    required: false
    default: 'false'
outputs:
  version:
    description: 'The version that was produced'
  changelog:
    description: 'changelog text'

runs:
  using: 'node16'
  main: 'dist/index.js'
