name: Changelog

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: ''

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Print
        run: |
          echo "version: ${{ inputs.version }}"
          echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build
        run: |
          npm install
          npm run build
          npm run package

      - name: Run Action
        uses: ./
        id: changelog
        with:
          version: ${{ inputs.version }}
          ignore-same-version-error: false
          ignore-less-version-error: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore(changelog): update CHANGELOG.md for v${{ steps.changelog.outputs.version }}"
          branch: changelog
          delete-branch: true
          title: 'Changelog v${{ steps.changelog.outputs.version }}'
          body: ${{ steps.changelog.outputs.changelog }}
          assignees: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
