name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        default: ''
      generate-changelog:
        type: choice
        default: auto
        options:
          - never
          - always
          - auto
      create_pr_for_branch:
        required: false
        default: 'main'
        description: Target branch? empty for skip.

permissions:
  contents: write
  pull-requests: write

jobs:
  default:
    runs-on: ubuntu-latest

    # Limit branch:
    if: github.ref == 'refs/heads/dev'
    # Or
    #if: github.ref != 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Inputs
        uses: Payadel/inputs@v1.0.0
        id: inputs
        with:
          inputs: |
            - name: version
              default: ''
            - name: generate-changelog
              default: 'auto'
            - name: create_pr_for_branch
              default: 'main'
            - name: current-branch-name
              default: '$(git rev-parse --abbrev-ref HEAD)'

      - uses: Payadel/release-sv-action@v0.3.3
        id: release
        with:
          version: ${{ steps.inputs.outputs.version }}
          generate-changelog: ${{ steps.inputs.outputs.generate-changelog }}
          create-pr-for-branch: ${{ steps.inputs.outputs.create_pr_for_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print outputs
        run: |
          echo "version: ${{ steps.release.outputs.version }}"
          echo "pull-request-url: ${{ steps.release.outputs.pull-request-url }}"
          echo "release-filename: ${{ steps.release.outputs.release-filename }}"

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: '${{ steps.release.outputs.release-filename }}'
          allowUpdates: true
          body: ${{ steps.release.outputs.changelog }}
          tag: 'v${{ steps.release.outputs.version }}'
