name: 'build-test'
on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          npm install

      - name: Run All
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run all

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run Action
        uses: ./
        id: changelog
        with:
          version: '1.0.0'

      - name: Get the output
        run: |
          echo "Outputs:"
          echo "Version: ${{ steps.changelog.outputs.version }}"
          echo "Changelog: ${{ steps.changelog.outputs.changelog }}"
        if: steps.changelog.outcome == 'success'
